# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadesmodel',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AddField(
            model_name='actividadesmodel',
            name='imagen',
            field=models.CharField(default=datetime.datetime(2016, 6, 18, 21, 19, 13, 554419, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
