# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20160618_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadesmodel',
            name='imagen',
        ),
    ]
