# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_remove_actividadesmodel_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
