# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20160817_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadesmodel',
            name='key_press',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
