# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_auto_20160819_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadesmodel',
            name='key_press_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
