# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_actividadesmodel_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadesmodel',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
