# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_auto_20160825_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadesmodel',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
