# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_actividadesmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadesmodel',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
