# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 02:35
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_actividadesmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'F:\\original\\funnyd'), upload_to='./static/images/'),
        ),
    ]
