# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_auto_20160907_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
