# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelesmodel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
    ]
