# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0002_auto_20160618_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='soundModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='sounds/')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveles.nivelesModel')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
    ]
