# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0003_soundmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundmodel',
            options={'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AddField(
            model_name='soundmodel',
            name='piano_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
