# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0004_auto_20160815_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundmodel',
            name='file',
            field=models.FileField(upload_to='funnyd/static/sounds/'),
        ),
    ]
