# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-17 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0005_auto_20160815_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piano_notes', models.TextField(blank=True, null=True)),
                ('intentos', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='soundmodel',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo en Segundos'),
        ),
        migrations.AddField(
            model_name='intento',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveles.soundModel'),
        ),
    ]
