# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-17 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niveles', '0006_auto_20160817_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
