# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0008_auto_20160818_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
