# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0009_intento_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
