# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0012_intento_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intento',
            name='tiempo',
        ),
    ]
