# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0015_nivelesmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundmodel',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
