# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0018_auto_20160907_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelesmodel',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nivelesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
