# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0019_auto_20160914_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivelesmodel',
            name='actividad',
        ),
    ]
