# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_auto_20160914_1141'),
        ('niveles', '0020_remove_nivelesmodel_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelesmodel',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.actividadesModel'),
        ),
    ]
