# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0021_nivelesmodel_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivelesmodel',
            name='order',
        ),
    ]
