# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0022_remove_nivelesmodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelesmodel',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
